[versions]
javapoet = "0.7.0"
# Gradle plugins
foojay-resolver = "1.0.0"
kotlin = "2.2.10"
paperweight = "2.0.0-beta.18"
run-task = "3.0.0"
resource-factory = "1.3.1"
plugin-publish = "2.0.0"
maven-publish = "0.34.0"
buildconfig = "5.6.8"
shadow = "9.1.0"

# Default versions
minecraft = "1.21.8"

[libraries]
javapoet = { module = "com.palantir.javapoet:javapoet", version.ref = "javapoet" }

[plugins]
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
resource-factory = { id = "xyz.jpenilla.resource-factory", version.ref = "resource-factory" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
