[versions]
kotlinx-datetime = "0.7.1-0.6.x-compat"

kotlinx-coroutines = "1.10.2"
mccoroutine = "2.22.0"

configurate = "4.2.0"

exposed = "1.0.0-beta-5"
hikari-cp = "7.0.0"

commandapi = "10.1.2"
invui = "2.0.0-alpha.17"

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
mccoroutine-folia-api = { module = "com.github.shynixn.mccoroutine:mccoroutine-folia-api", version.ref = "mccoroutine" }
mccoroutine-folia-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-folia-core", version.ref = "mccoroutine" }

configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
configurate-extra-kotlin = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }

hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari-cp" }
exposed-bom = { module = "org.jetbrains.exposed:exposed-bom", version.ref = "exposed" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime" }

commandapi-bukkit-shade-mojmap = { module = "dev.jorel:commandapi-bukkit-shade-mojang-mapped", version.ref = "commandapi" }
commandapi-bukkit-kotlin = { module = "dev.jorel:commandapi-bukkit-kotlin", version.ref = "commandapi" }

invui = { module = "xyz.xenondevs.invui:invui", version.ref = "invui" }
invuiKotlin = { module = "xyz.xenondevs.invui:invui-kotlin", version.ref = "invui" }

[bundles]
exposed = ["exposed-core", "exposed-jdbc", "exposed-dao", "exposed-kotlin-datetime"]
