name: Gradle publish
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    outputs:
      release-created: ${{ steps.release.outputs.release-created }}

    steps:
      - name: Release Please Action
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json

  publish:
    needs: release
    if: needs.release.outputs.release-created == 'true'
    runs-on: ubuntu-latest
    environment: Vela Releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get JDK version
        run: echo "JDK_VERSION=$(grep 'java.version' gradle-plugin/gradle.properties | cut -d '=' -f2)" >> "$GITHUB_ENV"

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ env.JDK_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Publish with Gradle
        id: publish
        run: ./gradlew gradle-plugin:publish publish
        env:
          VELA_USERNAME: ${{ secrets.VELA_USERNAME }}
          VELA_PASSWORD: ${{ secrets.VELA_PASSWORD }}
