name: Gradle publish
on:
  push:
    branches:
      - main

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    outputs:
      release-created: ${{ steps.release.outputs.releases_created }}
      tag-name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: Release Please Action
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json

  publish:
    needs: release
    if: needs.release.outputs.release-created == 'true'
    runs-on: ubuntu-latest
    environment: Vela Releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get JDK version
        run: echo "JDK_VERSION=$(grep 'java.version' gradle-plugin/gradle.properties | cut -d '=' -f2)" >> "$GITHUB_ENV"

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ env.JDK_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Publish gradle plugin
        id: publish-gradle-plugin
        run: ./gradlew gradle-plugin:publish
        env:
          VELA_USERNAME: ${{ secrets.VELA_USERNAME }}
          VELA_PASSWORD: ${{ secrets.VELA_PASSWORD }}

      - name: Publish libraries
        id: publish-artifacts
        run: ./gradlew publish --no-configuration-cache # Temporarily disable configuration cache due to task issues
        env:
          VELA_USERNAME: ${{ secrets.VELA_USERNAME }}
          VELA_PASSWORD: ${{ secrets.VELA_PASSWORD }}

      - name: Build phantom-paper-plugin
        run: ./gradlew phantom-paper-plugin:build

      - name: Upload phantom-paper-plugin release artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload \
          ${{ needs.release.outputs.tag-name }} \
          paper-plugin/build/libs/*.jar \
          --clobber \
